use_frameworks!

project 'PasseiJWT.xcodeproj'
 
platform :ios, '14.0'

target 'PasseiJWT_Example' do
  use_frameworks!
  pod 'PasseiLogManager', :git => 'https://github.com/ziminny/PasseiLogManager.git'
  pod 'PasseiJWT', :path => '../'

  target 'PasseiJWT_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
