use_frameworks!

project 'PasseiJWT.xcodeproj'

platform :ios, '10.0'

target 'PasseiJWT_Example' do
  pod 'PasseiJWT', :path => '../'

  target 'PasseiJWT_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
